#!/bin/sh
echo "Running pre-commit checks..."

./gradlew spotlessApply
SPOTLESS_RESULT=$?

./gradlew detekt
DETEKT_RESULT=$?

if [ $SPOTLESS_RESULT -ne 0 ] || [ $DETEKT_RESULT -ne 0 ]; then
    echo "Pre-commit checks failed. Commit aborted."
    exit 1
fi

echo "Pre-commit checks passed. Proceeding with commit."
exit 0
